version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  llm-backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    env_file:
      - .env
